services:
  - type: web
    name: hive-hms
    env: php
    region: singapore
    plan: free
    buildCommand: composer install --no-dev --optimize-autoloader && php artisan key:generate --force && npm install && npm run build && php artisan migrate --force
    startCommand: heroku-php-apache2 public/
    envVars:
      - key: APP_NAME
        value: Hive
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://hive-hms.onrender.com
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: hive-db
          property: connectionString
      - key: APP_KEY
        generateValue: true
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_LIFETIME
        value: 120
      - key: SESSION_SECURE_COOKIE
        value: true
      - key: TELESCOPE_ENABLED
        value: false

databases:
  - name: hive-db
    region: singapore
    plan: free
    databaseName: hive
    user: hive_user

